# Generated by Django 5.2.5 on 2025-09-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='document_path',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='document_content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
