# Generated by Django 5.2.5 on 2025-09-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0002_remove_chatsession_document_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
