# Generated by Django 5.2.5 on 2025-09-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0003_alter_chatmessage_options_remove_chatsession_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='New Chat', max_length=100),
        ),
    ]
