# Generated by Django 5.2.5 on 2025-09-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPT', '0004_alter_chatmessage_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='document_content',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='document_name',
        ),
    ]
