"""
Django settings for techjaysGPT project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
env_path = BASE_DIR / '.env'
if env_path.exists():
    print(f"INFO: Loading environment variables from {env_path}")
    load_dotenv(dotenv_path=env_path)
else:
    print(f"WARNING: .env file not found at {env_path}. Using default settings or expecting environment variables.")

# --- Core Settings ---

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'a-default-insecure-key-for-development-only')

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False if not set. Recommended to set DEBUG=True in .env for local dev.
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# --- ALLOWED_HOSTS ---
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Add hosts from environment variable (for production)
env_hosts = os.getenv('ALLOWED_HOSTS')
if env_hosts:
    ALLOWED_HOSTS.extend([host.strip() for host in env_hosts.split(',')])

# Add Render.com hostname for easy deployment
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic', # For serving static files in production

    # Your applications
    'GPT',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # WhiteNoise middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'techjaysGPT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'techjaysGPT.wsgi.application'

#postgresql://techjays_gpt_db_user:oVYEQItxe0bADQyX1EE57j7EQXQQ1NPn@dpg-d2r7ca15pdvs738umn00-a.oregon-postgres.render.com/techjays_gpt_db
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Using dj-database-url to parse a single DATABASE_URL from the environment.
# This is a standard practice for modern Django applications and simplifies deployment.
DATABASES = {
    'default': dj_database_url.config(
        # Fallback to a local SQLite DB if DATABASE_URL is not set.
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,  # Keep connections alive for 10 minutes
        ssl_require=not DEBUG # Enable SSL for production DB, disable for local SQLite.
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / 'staticfiles' # Directory for collectstatic
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirect users to the 'home' view after a successful login.
LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'


# Media (for uploaded docs)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Chroma persistent directory (per-session subfolders will be created)
CHROMA_DIR = BASE_DIR / 'chroma'

# --- Production Security Settings ---
# These settings are enabled when DEBUG is False.
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# For HSTS, start with a low value and increase once you confirm it works.
SECURE_HSTS_SECONDS = 2592000  # 30 days

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': { 
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s',
            'datefmt': '%d/%b/%Y %H:%M:%S'
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'GPT': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    }
}

# --- Directory Creation ---
# Ensure that directories required by the application exist upon startup.
# This prevents startup warnings (like for staticfiles) and runtime errors.
for path in [
    STATIC_ROOT,
    MEDIA_ROOT,
    CHROMA_DIR,
] + STATICFILES_DIRS:
    os.makedirs(path, exist_ok=True)